from langchain_core.prompts import PromptTemplate

RESUME_PROMPT = PromptTemplate(
    input_variables=["resume_text", "job_description"],
    template="""You are an expert technical recruiter analyzing a resume.
    Job Description:
    {job_description}
    
    Resume Text:
    {resume_text}
    
    Task: Output a score (0-100) reflecting how well this resume matches the job description in terms of syntax, clarity, impact metrics, and skills. Provide a single sentence of reasoning, and list up to 3 specific positive/negative signals.
    """
)

GITHUB_PROMPT = PromptTemplate(
    input_variables=["github_username", "job_description"],
    template="""You are an expert Staff Software Engineer reviewing a candidate's GitHub profile.
    Job Role Target:
    {job_description}
    
    Candidate GitHub Profile Data (real scraped data as JSON):
    {github_username}
    
    Task: Based on ONLY the real data above, output a score (0-100) evaluating the candidate's GitHub activity. 
    Consider: number of repos, stars, language diversity, top project descriptions, and alignment with the job role.
    Provide a concrete single-sentence reasoning and up to 3 specific signals derived from the actual data above.
    Do NOT invent or assume data not present. If data is sparse, reflect that in a lower score.
    """
)

LEETCODE_PROMPT = PromptTemplate(
    input_variables=["leetcode_id", "job_description"],
    template="""You are an expert algorithmic interviewer reviewing a candidate's LeetCode statistics.
    Job Role Target:
    {job_description}
    
    Candidate LeetCode Profile Data (real scraped stats as JSON):
    {leetcode_id}
    
    Task: Based on ONLY the real data above, output a score (0-100) evaluating the candidate's algorithm and data structure capability.
    Consider: total problems solved, difficulty breakdown (Easy/Medium/Hard), global ranking, contest rating, and active days.
    Provide a concrete single-sentence reasoning and up to 3 specific signals derived from the actual data.
    Do NOT invent or assume data not present.
    """
)

LINKEDIN_PROMPT = PromptTemplate(
    input_variables=["linkedin_url", "job_description"],
    template="""You are an HR manager evaluating a candidate's professional profile.
    Job Role Target:
    {job_description}
    
    Candidate Profile Information:
    {linkedin_url}
    
    Task: Based on the profile information above, output a score (0-100) reflecting the candidate's professional pedigree.
    Consider: work experience, education, endorsements, career progression, and alignment with the job role.
    If the profile text is limited or unavailable, base your score on the resume/candidate information provided and explicitly note this in your reasoning.
    Provide a single-sentence reasoning and up to 3 specific signals.
    """
)

DEBATE_PROMPT = PromptTemplate(
    input_variables=["component_scores"],
    template="""You are a Senior Technical Hiring Panel AI.
Review the independent evaluations generated by parallel agents:
{component_scores}

Your Constraints:
1. Detect inconsistencies (e.g., claimed 10 years experience on Resume, but GitHub shows beginner commits).
2. Identify compensation patterns (e.g., weak LeetCode but exceptionally strong GitHub system design projects).
3. You may adjust base weights by exactly +/- 0.05 per component ONLY if strongly justified by a compensation pattern. Sum of adjustments MUST equal 0.
4. If no adjustments are needed, set all weight offsets to 0.0.
5. Inconsistencies flagged should be a list of string observations.
6. Return output strictly conforming to the requested schema. Do not hallucinate data. Be deterministic.
    """
)

